/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grothagar;

/**
 *
 * @author Tipu
 */
public class Aboutus extends javax.swing.JFrame {

    /**
     * Creates new form Aboutus
     */
    public Aboutus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        heading = new javax.swing.JLabel();
        librarylogo = new javax.swing.JLabel();
        aboutus = new javax.swing.JLabel();
        nameofkalam = new javax.swing.JLabel();
        kalam = new javax.swing.JLabel();
        niam = new javax.swing.JLabel();
        mridula = new javax.swing.JLabel();
        jhumu = new javax.swing.JLabel();
        nameofjhumu = new javax.swing.JLabel();
        suzon = new javax.swing.JLabel();
        nameofsuzon = new javax.swing.JLabel();
        nameofniam = new javax.swing.JLabel();
        nameofmridula = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Developer");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        heading.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        heading.setText("Library Management System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 10, 0, 0);
        getContentPane().add(heading, gridBagConstraints);

        librarylogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/liicon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 101, 0, 0);
        getContentPane().add(librarylogo, gridBagConstraints);

        aboutus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aboutus.setText("About Us");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 46, 0, 0);
        getContentPane().add(aboutus, gridBagConstraints);

        nameofkalam.setText("Kalam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 111, 0, 0);
        getContentPane().add(nameofkalam, gridBagConstraints);

        kalam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tt.JPG"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 61, 0, 0);
        getContentPane().add(kalam, gridBagConstraints);

        niam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/niam.jpg"))); // NOI18N
        niam.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 32;
        gridBagConstraints.ipadx = -48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 30, 0, 161);
        getContentPane().add(niam, gridBagConstraints);

        mridula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mm.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 141, 0, 0);
        getContentPane().add(mridula, gridBagConstraints);

        jhumu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/zz.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 31, 0, 0);
        getContentPane().add(jhumu, gridBagConstraints);

        nameofjhumu.setText("Jhumu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(nameofjhumu, gridBagConstraints);

        suzon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/szn.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 6, 0, 0);
        getContentPane().add(suzon, gridBagConstraints);

        nameofsuzon.setText("Suzon");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(nameofsuzon, gridBagConstraints);

        nameofniam.setText("Niam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 34;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 0, 0, 0);
        getContentPane().add(nameofniam, gridBagConstraints);

        nameofmridula.setText("Mridula");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 56, 0, 0);
        getContentPane().add(nameofmridula, gridBagConstraints);

        homebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hom.png"))); // NOI18N
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = -28;
        gridBagConstraints.ipady = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 11, 0);
        getContentPane().add(homebtn, gridBagConstraints);

        setSize(new java.awt.Dimension(837, 578));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home hm = new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutus;
    private javax.swing.JLabel heading;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jhumu;
    private javax.swing.JLabel kalam;
    private javax.swing.JLabel librarylogo;
    private javax.swing.JLabel mridula;
    private javax.swing.JLabel nameofjhumu;
    private javax.swing.JLabel nameofkalam;
    private javax.swing.JLabel nameofmridula;
    private javax.swing.JLabel nameofniam;
    private javax.swing.JLabel nameofsuzon;
    private javax.swing.JLabel niam;
    private javax.swing.JLabel suzon;
    // End of variables declaration//GEN-END:variables
}
