/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grothagar;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
//pdf
import com.itextpdf.text.BaseColor;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
 
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
//end pdf

/**
 *
 * @author Tipu
 */
public class Booklist extends javax.swing.JFrame {

    /**
     * Creates new form Booklist
     */
    public Booklist() {
        initComponents();
        fetch_books();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    // Retrive book information from database..
     public void fetch_books(){
   
       Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
       try{
           String query = "select * from books";
           con = Db.getConnection();
           stmt = con.createStatement();
           rs = stmt.executeQuery(query);
           booktable.setModel(DbUtils.resultSetToTableModel(rs));

           booktable.setAutoResizeMode(booktable.AUTO_RESIZE_LAST_COLUMN);
           booktable.setRowHeight(30);
           booktable.getColumnModel().getColumn(0).setMaxWidth(50);
           booktable.getColumnModel().getColumn(2).setMinWidth(160);
           booktable.getColumnModel().getColumn(3).setMinWidth(100);
           booktable.getColumnModel().getColumn(4).setMinWidth(120);
           booktable.getColumnModel().getColumn(5).setMinWidth(130);
        }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();
                stmt.close();
                con.close();
            }catch(Exception ee){
                JOptionPane.showMessageDialog(null,"Connection error","Warning",JOptionPane.WARNING_MESSAGE);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        delbtn = new javax.swing.JButton();
        editBookinfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        lb_bookshelf = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        book_logo = new javax.swing.JLabel();
        savepdf_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf_bookid = new javax.swing.JTextField();
        tf_publisher = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_edition = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_isbn = new javax.swing.JTextField();
        tf_pages = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_book_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_author = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book List");
        setBackground(new java.awt.Color(0, 153, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        delbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delbtn.setForeground(new java.awt.Color(51, 153, 255));
        delbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rem.png"))); // NOI18N
        delbtn.setText("Delete Book");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        editBookinfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editBookinfo.setForeground(new java.awt.Color(0, 153, 153));
        editBookinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        editBookinfo.setText("Edit Book Info");
        editBookinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBookinfoActionPerformed(evt);
            }
        });

        booktable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        booktable.setMinimumSize(new java.awt.Dimension(60, 70));
        jScrollPane1.setViewportView(booktable);

        lb_bookshelf.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lb_bookshelf.setForeground(new java.awt.Color(255, 255, 255));
        lb_bookshelf.setText("Bookshelf");

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hom.png"))); // NOI18N
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        book_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libook.png"))); // NOI18N

        savepdf_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        savepdf_btn.setText("Save as PDF");
        savepdf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepdf_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addComponent(book_logo)
                                .addGap(28, 28, 28)
                                .addComponent(lb_bookshelf, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)
                                .addComponent(delbtn)
                                .addGap(71, 71, 71)
                                .addComponent(editBookinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(savepdf_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(book_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lb_bookshelf, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editBookinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(savepdf_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        tf_bookid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tf_publisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Book ID: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Pages: ");

        tf_edition.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Edition: ");

        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updt.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Author:");

        tf_isbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Publisher: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name: ");

        tf_book_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ISBN No:");

        tf_author.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_authorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(tf_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addComponent(tf_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(tf_author, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(tf_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addGap(50, 50, 50)
                        .addComponent(tf_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(tf_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_author, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tf_edition, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(update_btn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1272, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home hm = new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_home_btnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        //Delete selected table
        Connection conn = null;
        PreparedStatement ps = null;
        DefaultTableModel model= (DefaultTableModel)booktable.getModel();
        int row = booktable.getSelectedRow();
        String selected = model.getValueAt(row, 0).toString();

        if (row >= 0) {
            model.removeRow(row);
            try {
                conn = Db.getConnection();
                ps = conn.prepareStatement("delete from books where Serial='"+selected+"' ");
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null," Book Deleted Successfully !","Success",JOptionPane.INFORMATION_MESSAGE);

            }catch(Exception ee){
                JOptionPane.showMessageDialog(null,"Error during Delete !","warning",JOptionPane.FRAMEBITS);
            }finally{
                try{
                    ps.close();
                    conn.close();
                }catch(Exception eee){
                    JOptionPane.showMessageDialog(null,"Connection Error !","warning",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_delbtnActionPerformed

    private void editBookinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBookinfoActionPerformed
        // TODO add your handling code here:
        //set selected value in TextField
        DefaultTableModel model= (DefaultTableModel)booktable.getModel();
        int row = booktable.getSelectedRow();

        String sl = model.getValueAt(row, 0).toString();
        String bid = model.getValueAt(row, 1).toString();
        String name = model.getValueAt(row, 2).toString();
        String author = model.getValueAt(row, 3).toString();
        String pub = model.getValueAt(row, 4).toString();
        String isbn = model.getValueAt(row, 5).toString();
        String edition = model.getValueAt(row, 6).toString();
        String pages = model.getValueAt(row, 7).toString();

        tf_bookid.setText(bid);
        tf_book_name.setText(name);
        tf_author.setText(author);
        tf_publisher.setText(pub);
        tf_isbn.setText(isbn);
        tf_edition.setText(edition);
        tf_pages.setText(pages);

    }//GEN-LAST:event_editBookinfoActionPerformed

    private void tf_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_authorActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        
        //update book information
        Connection conn = null;
        PreparedStatement ps = null;
        try{
            conn = Db.getConnection();
            int bid = Integer.parseInt(tf_bookid.getText());
            String name = tf_book_name.getText();
            String author = tf_author.getText();
            String publisher = tf_publisher.getText();
            String isbn = tf_isbn.getText();
            String edition = tf_edition.getText();
            int pages = Integer.parseInt(tf_pages.getText());

            String query = "UPDATE books SET Book_Name = ?, Author= ?,Publisher = ?, ISBN_No = ?,Edition= ?, Pages= ? WHERE Book_ID = ?";
            ps = conn.prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, author);
            ps.setString(3, publisher);
            ps.setString(4, isbn);
            ps.setString(5, edition);
            ps.setInt(6, pages);
            ps.setInt(7, bid);
            ps.executeUpdate();
            fetch_books();
            JOptionPane.showMessageDialog(null,"Information Updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);

        }catch(Exception ee){
            JOptionPane.showMessageDialog(null,"Error during Update","warning",JOptionPane.WARNING_MESSAGE);
        }finally{
            try{
                ps.close();
                conn.close();
            }catch(Exception eee){
                JOptionPane.showMessageDialog(null,"Connection Error","warning",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void savepdf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepdf_btnActionPerformed
        // TODO add your handling code here:
        //generate pdf report of members
        Connection conn = null;
        Document d = new Document();
        ResultSetMetaData rmd = null;
        ResultSet rs = null;
        Statement stmt = null;
        try
        {
            //code
            conn = Db.getConnection();
            String query = "select * from books";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(query);
            rmd = rs.getMetaData();
            int coln = rmd.getColumnCount();
            int rowno = 0;
            while(rs.next()){
                rowno++;
            }
            rs.first();

            PdfWriter writer = PdfWriter.getInstance(d,new FileOutputStream("booklist.pdf"));
            PdfPTable pt = new PdfPTable(coln);
            d.open();

            Paragraph wrong = new Paragraph("Library Management\nGroup Name: Swing\n---------------------------");

            wrong.setIndentationLeft(200);
            d.add(wrong);
            d.add(new Paragraph(" "));
            PdfPCell cell = new PdfPCell(new Paragraph("Book list"));
            cell.setColspan(coln);
            cell.setBackgroundColor(BaseColor.CYAN);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            pt.addCell(cell);
                pt.addCell("Serial");
                pt.addCell("Book_ID");
                pt.addCell("Book_Name");
                pt.addCell("Author");
                pt.addCell("Publisher");
                pt.addCell("ISBN_No");
                pt.addCell("Edition");
                pt.addCell("Pages");
            for(int i=0;i<rowno;i++){
                //pt.addCell(""+rs.getString(i+1));
                for(int j = 1;j <=coln; j++){
                    pt.addCell(""+rs.getString(j));
                }
                rs.next();
            }
            d.add(pt);
            d.close();
            writer.close();
            JOptionPane.showMessageDialog(null, "Report generated successfully");
            //end

        }catch (Exception ee){
            ee.printStackTrace();
        }finally{
            try{
                rs.close();
                conn.close();
            }catch(Exception eee){
                eee.printStackTrace();
            }
        }
    }//GEN-LAST:event_savepdf_btnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_logo;
    private javax.swing.JTable booktable;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton editBookinfo;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_bookshelf;
    private javax.swing.JButton savepdf_btn;
    private javax.swing.JTextField tf_author;
    private javax.swing.JTextField tf_book_name;
    private javax.swing.JTextField tf_bookid;
    private javax.swing.JTextField tf_edition;
    private javax.swing.JTextField tf_isbn;
    private javax.swing.JTextField tf_pages;
    private javax.swing.JTextField tf_publisher;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
