/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grothagar;
import com.itextpdf.text.BaseColor;
import java.sql.*;
import javax.swing.JFrame;
//pdf

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
 
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
//end pdf
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tipu
 */
public class Showmember extends javax.swing.JFrame {

    /**
     * Creates new form Show member
     */
    public Showmember() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        fetch_members();
    }
    
    //Fetch members details
    public void fetch_members(){
       Connection con = null;
        Statement stmt = null;
        ResultSet rs = null;
       try{
           String query = "select * from member";
           con = Db.getConnection();
           stmt = con.createStatement();
           rs = stmt.executeQuery(query);
           memtable.setModel(DbUtils.resultSetToTableModel(rs));

           memtable.setAutoResizeMode(memtable.AUTO_RESIZE_LAST_COLUMN);
           memtable.setRowHeight(30);
           memtable.getColumnModel().getColumn(3).setMinWidth(160);
        }catch(Exception e){
                  JOptionPane.showMessageDialog(null, e);
        }finally {
            try{
                rs.close();
                stmt.close();
                con.close();
            }catch(Exception ee){
                JOptionPane.showMessageDialog(null,"Connection error","Warning",JOptionPane.WARNING_MESSAGE);
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        memtable = new javax.swing.JTable();
        delbtn = new javax.swing.JButton();
        editdetails_btn = new javax.swing.JButton();
        heading = new javax.swing.JLabel();
        user_logo = new javax.swing.JLabel();
        home_btn = new javax.swing.JButton();
        savepdf_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf_address = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_semester = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_st_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_st_namea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Members");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        memtable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        memtable.setMinimumSize(new java.awt.Dimension(60, 70));
        jScrollPane1.setViewportView(memtable);

        delbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delbtn.setForeground(new java.awt.Color(51, 153, 255));
        delbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rem.png"))); // NOI18N
        delbtn.setText("Delete Member");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        editdetails_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editdetails_btn.setForeground(new java.awt.Color(0, 153, 153));
        editdetails_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        editdetails_btn.setText("Edit Details");
        editdetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdetails_btnActionPerformed(evt);
            }
        });

        heading.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(0, 153, 153));
        heading.setText("All registered member list");

        user_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limember.png"))); // NOI18N

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hom.png"))); // NOI18N
        home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_btnActionPerformed(evt);
            }
        });

        savepdf_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        savepdf_btn.setText("Save as PDF");
        savepdf_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepdf_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(delbtn)
                        .addGap(36, 36, 36)
                        .addComponent(editdetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(savepdf_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(user_logo)
                        .addGap(18, 18, 18)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(user_logo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delbtn)
                            .addComponent(editdetails_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savepdf_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(home_btn)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        tf_address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tf_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("E-mail:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Student ID:");

        tf_contact.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Contact: ");

        tf_semester.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_semester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_semesterActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Semester: ");

        tf_st_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address: ");

        tf_st_namea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/minilogo.png"))); // NOI18N
        jLabel9.setText("Update Member Information");

        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/updt.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_contact)
                    .addComponent(tf_st_id)
                    .addComponent(tf_st_namea)
                    .addComponent(tf_semester)
                    .addComponent(tf_email)
                    .addComponent(tf_address)
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel9)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_st_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_st_namea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(38, 38, 38)
                .addComponent(update_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1137, 632));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here
    }//GEN-LAST:event_formWindowOpened

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        PreparedStatement ps = null;
            DefaultTableModel model= (DefaultTableModel)memtable.getModel();
            int row = memtable.getSelectedRow();
            String selected = model.getValueAt(row, 0).toString();

            if (row >= 0) {
                model.removeRow(row);
                try {
                    conn = Db.getConnection();
                    ps = conn.prepareStatement("delete from member where Student_ID='"+selected+"' ");
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null," Member Deleted Successfully !","Success",JOptionPane.INFORMATION_MESSAGE);
                    
                }catch(Exception ee){
            JOptionPane.showMessageDialog(null,"Error in Delete !","warning",JOptionPane.FRAMEBITS);
        }finally{
            try{
                ps.close();
                conn.close();
            }catch(Exception eee){
                JOptionPane.showMessageDialog(null,"Connection Error !","warning",JOptionPane.ERROR_MESSAGE);
                }
            }       
        }
    }//GEN-LAST:event_delbtnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement ps = null;
        try{
            conn = Db.getConnection();
            int id = Integer.parseInt(tf_st_id.getText());
            String name = tf_st_namea.getText();
            String semes = tf_semester.getText();
            String email = tf_email.getText();
            String contact = tf_contact.getText();
            String addr = tf_address.getText();
            
            String query = "UPDATE member SET Name = ?, Semester= ?,Email = ?, Contact = ?,Address= ? WHERE Student_ID = ?";
            ps = conn.prepareStatement(query);
            ps.setString(1, name);
            ps.setString(2, semes);
            ps.setString(3, email);
            ps.setString(4, contact);
            ps.setString(5, addr);
            ps.setInt(6, id);
            ps.executeUpdate();
            fetch_members();
             JOptionPane.showMessageDialog(null,"Information Updated Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            
        }catch(Exception ee){
            JOptionPane.showMessageDialog(null,"Error in Update","warning",JOptionPane.WARNING_MESSAGE);
        }finally{
            try{
                ps.close();
                conn.close();
            }catch(Exception eee){
                JOptionPane.showMessageDialog(null,"Connection Error","warning",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void editdetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdetails_btnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model= (DefaultTableModel)memtable.getModel();
        int row = memtable.getSelectedRow();

             String id = model.getValueAt(row, 0).toString();
             String name = model.getValueAt(row, 1).toString();
             String seme = model.getValueAt(row, 2).toString();
             String email = model.getValueAt(row, 3).toString();
             String contact = model.getValueAt(row, 4).toString();
             String addr = model.getValueAt(row, 5).toString();
           
             tf_st_id.setText(id);
             tf_st_namea.setText(name);
             tf_semester.setText(seme);
             tf_email.setText(email);
             tf_contact.setText(contact);
             tf_address.setText(addr);
             
   
    }//GEN-LAST:event_editdetails_btnActionPerformed

    private void tf_semesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_semesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_semesterActionPerformed

    private void home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home hm = new Home();
        hm.setVisible(true);
    }//GEN-LAST:event_home_btnActionPerformed

    private void savepdf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepdf_btnActionPerformed
        // TODO add your handling code here:
        //generate pdf report of members
          Connection conn = null;
          Document d = new Document();
          ResultSetMetaData rmd = null;
          ResultSet rs = null;
          Statement stmt = null;
      try
      {
          //code
                conn = Db.getConnection();
                String query = "select * from member";
                stmt = conn.createStatement();
                rs = stmt.executeQuery(query);
		rmd = rs.getMetaData();
		int coln = rmd.getColumnCount();
		int rowno = 0;
		while(rs.next()){
			rowno++;
		}
		rs.first();
                
		PdfWriter writer = PdfWriter.getInstance(d,new FileOutputStream("memberlist.pdf"));
		PdfPTable pt = new PdfPTable(coln);
		d.open();
              
                Paragraph wrong = new Paragraph("Library Management\nGroup Name: Swing\n---------------------------");
                
                wrong.setIndentationLeft(200);
                d.add(wrong);
                d.add(new Paragraph(" "));
                PdfPCell cell = new PdfPCell(new Paragraph("All Member list"));
                cell.setColspan(coln);
                cell.setBackgroundColor(BaseColor.CYAN);
                cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                pt.addCell(cell);
                pt.addCell("ID");
                pt.addCell("Name");
                pt.addCell("Semester");
                pt.addCell("Email");
                pt.addCell("Phone");
                pt.addCell("Address");
		for(int i=0;i<rowno;i++){
                    //pt.addCell(""+rs.getString(i+1));
                    for(int j = 1;j <=coln; j++){    
			pt.addCell(""+rs.getString(j));
                    }
                    rs.next();
		}
                d.add(pt);
		d.close();
		 writer.close();
                  JOptionPane.showMessageDialog(null, "Report generated successfully");
                //end

      }catch (Exception ee){
         ee.printStackTrace();
      }finally{
         try{ 
             rs.close();
             conn.close();
         }catch(Exception eee){
              eee.printStackTrace();
         }
      }
    }//GEN-LAST:event_savepdf_btnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delbtn;
    private javax.swing.JButton editdetails_btn;
    private javax.swing.JLabel heading;
    private javax.swing.JButton home_btn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable memtable;
    private javax.swing.JButton savepdf_btn;
    private javax.swing.JTextField tf_address;
    private javax.swing.JTextField tf_contact;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_semester;
    private javax.swing.JTextField tf_st_id;
    private javax.swing.JTextField tf_st_namea;
    private javax.swing.JButton update_btn;
    private javax.swing.JLabel user_logo;
    // End of variables declaration//GEN-END:variables
}
